import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PublicKey } from '@solana/web3.js';
import { deriveGoalBinding, configurationHash, validateBinding, createVaultCalldata, financialInstruction, initializeInstruction, ABI, word, addressWord, solanaAddressWord } from '../src/chain/codec.js';
import { assertEvmEnvelope, creationPatch, assertTokenEvent, reconcile, type EvmReceipt, type EvmTransaction } from '../src/chain/receipt.js';
import { planFingerprint, assertPlan, assertActionState } from '../src/chain/planner.js';
import { ReadOnlyRpc, type RpcTransport } from '../src/chain/rpc.js';
import { combineState } from '../src/chain/state.js';
import type { DecodedGoal } from '../src/chain/codec.js';
import { EVM_DEPLOYMENTS, type GoalBinding, type ChainPlan, type GoalChainState, type GoalPositionState } from '@nabungfi/shared/chain';
const owner = { solana: 'AMoZFFdhUaNq8qyVRE4RrdW7rBc5Jssc6b7MyERMB7s8', evm: '0xc82f469aa95a2f7792300c8d11230e9023a98600' }, id = '0x' + '1'.repeat(64);
const binding = () => deriveGoalBinding({ goalId: id, targetRaw: '8000000', owner, networks: ['solana', 'base', 'arbitrum', 'ethereum'] });
const complete = () => {
    const b = binding();
    for (const p of b.participants) {
        p.vault = '0x' + '3'.repeat(40);
        p.configHash = configurationHash(b, p, p.vault);
    }
    return b;
};
const plan = (b: GoalBinding, action: ChainPlan['action'] = 'deposit'): ChainPlan => { const p = b.participants[0]!; const unsigned = { id: 'server-step-1', goalId: b.goalId, action, network: 'base' as const, owner: b.owner.evm, amountRaw: '1000000', createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 300000).toISOString(), transaction: { kind: 'evm' as const, chainId: 84532, to: p.vault!, data: '0x' + ABI.deposit + word('1000000'), value: '0' } }; return { ...unsigned, fingerprint: planFingerprint(unsigned) }; };
test('goal seeds isolate owners and IDs; canonical networks cannot be substituted', () => { const a = binding(), second = deriveGoalBinding({ goalId: '0x' + '2'.repeat(64), targetRaw: '8000000', owner, networks: ['solana', 'base'] }); assert.notEqual(a.solanaGoal, second.solanaGoal); assert.throws(() => validateBinding({ ...a, solanaGoal: second.solanaGoal })); assert.throws(() => deriveGoalBinding({ goalId: id, targetRaw: '8000000', owner, networks: ['base'] })); assert.throws(() => validateBinding({ ...a, participants: a.participants.map((p, i) => i === 0 ? { ...p, asset: EVM_DEPLOYMENTS.ethereum.asset } : p) })); });
test('same EVM vault address in different domains has distinct valid leaf hashes', () => { const b = complete(); validateBinding(b); assert.notEqual(b.participants[1]!.configHash, b.participants[2]!.configHash); const wrong = { ...b, participants: b.participants.map((p, i) => i === 2 ? { ...p, configHash: b.participants[1]!.configHash } : p) }; assert.throws(() => validateBinding(wrong)); });
test('configuration codec agrees with published golden preimages', () => {
    const fixture = JSON.parse(readFileSync(new URL('../../../shared/protocol/wire-v2.json', import.meta.url), 'utf8'));
    const cfg = fixture.config, b = { ...binding(), goalId: cfg.goalId, targetRaw: String(cfg.target), owner: { solana: new PublicKey(Buffer.from(cfg.solanaOwner.slice(2), 'hex')).toBase58(), evm: '0x' + fixture.pairs[0].owner.slice(-40) }, solanaGoal: new PublicKey(Buffer.from(cfg.solanaGoal.slice(2), 'hex')).toBase58() };
    for (const pair of fixture.pairs) {
        const p = { ...b.participants.find(p => p.domain === pair.domain)!, asset: '0x' + pair.asset.slice(-40), router: '0x' + pair.router.slice(-40) };
        assert.equal(configurationHash(b, p, '0x' + pair.vault.slice(-40)), pair.expectedHash);
    }
});
test('unsigned wallet codecs use the owner, exact finite amounts and correct core accounts', () => { const b = complete(); assert.equal(createVaultCalldata(b).slice(0, 10), '0x00f16bd1'); const init = initializeInstruction(b); assert.equal(init.keys[0]!.pubkey.toBase58(), owner.solana); assert.equal(init.keys.filter(k => k.isSigner).length, 1); const deposit = financialInstruction(b, 'deposit', '1000000'); assert.equal(deposit.data.readBigUInt64LE(8), 1000000n); assert.equal(deposit.keys[1]!.pubkey.toBase58(), b.solanaGoal); assert.throws(() => initializeInstruction(binding())); });
test('plan fingerprint survives JSONB ordering and rejects wallet/network/calldata substitution', () => {
    const b = complete(), p = plan(b);
    const reordered = Object.fromEntries(Object.entries(p).reverse()) as unknown as ChainPlan;
    assertPlan(b, reordered);
    for (const changed of [{ ...p, owner: '0x' + '4'.repeat(40) }, { ...p, transaction: { ...p.transaction, data: '0xdead' } }, { ...p, network: 'arbitrum' as const }])
        assert.throws(() => assertPlan(b, changed as ChainPlan));
});
test('foreign caller, sibling vault, amount, network and native value cannot confirm a wallet step', () => {
    const b = complete(), p = plan(b), tx: EvmTransaction = { hash: '0x' + '5'.repeat(64), from: p.owner, to: (p.transaction as any).to, input: (p.transaction as any).data, value: '0x0', chainId: '0x14a34' };
    assertEvmEnvelope(p, tx);
    for (const changed of [{ ...tx, from: '0x' + '4'.repeat(40) }, { ...tx, to: '0x' + '6'.repeat(40) }, { ...tx, input: '0x' + ABI.deposit + word('2000000') }, { ...tx, value: '0x1' }, { ...tx, chainId: '0x1' }])
        assert.throws(() => assertEvmEnvelope(p, changed));
});
test('creation event binds the actual concurrent CREATE result', () => { const b = binding(), p = b.participants[0]!, vault = '0x' + '8'.repeat(40), hash = configurationHash(b, p, vault), receipt: EvmReceipt = { transactionHash: '0x' + '5'.repeat(64), status: '0x1', blockNumber: '0x1', blockHash: '0x' + '6'.repeat(64), logs: [{ address: p.router, topics: ['0x9d4c56aa1ee57230854bc61ae127f007cc16fbe66b8d5c088c2d3112708c9cc6', '0x' + addressWord(owner.evm), '0x' + addressWord(vault), '0x' + solanaAddressWord(b.solanaGoal)], data: b.goalId + hash.slice(2) }] }; const patch = creationPatch(b, 'base', receipt); assert('vault' in patch && patch.vault === vault); assert.throws(() => creationPatch({ ...b, goalId: '0x' + '9'.repeat(64) }, 'base', receipt)); assert.throws(() => creationPatch(b, 'arbitrum', receipt)); });
test('USDC receipt conservation requires canonical token, sender, recipient and amount', () => { const b = complete(), p = plan(b), peer = b.participants[0]!, receipt: EvmReceipt = { transactionHash: '0x' + '5'.repeat(64), status: '0x1', blockNumber: '0x1', blockHash: '0x' + '6'.repeat(64), logs: [{ address: peer.asset, topics: ['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef', '0x' + addressWord(owner.evm), '0x' + addressWord(peer.vault!)], data: '0x' + word('1000000') }] }; assertTokenEvent(b, p, receipt); assert.throws(() => assertTokenEvent(b, p, { ...receipt, logs: [{ ...receipt.logs[0]!, data: '0x' + word('999999') }] })); assert.throws(() => assertTokenEvent(b, p, { ...receipt, logs: [{ ...receipt.logs[0]!, address: EVM_DEPLOYMENTS.arbitrum.asset }] })); });
test('unobserved original receipt stays attention after expiry; RPC cannot broadcast', async () => { const b = complete(), p = plan(b); p.expiresAt = new Date(Date.now() - 10000).toISOString(); const { fingerprint, ...unsigned } = p; p.fingerprint = planFingerprint(unsigned); const rpc = { call: async (_n: string, m: string) => m === 'eth_chainId' ? '0x14a34' : null } as unknown as RpcTransport; const result = await reconcile(rpc, b, p, '0x' + '5'.repeat(64)); assert.equal(result.status, 'attention'); await assert.rejects(new ReadOnlyRpc().call('base', 'eth_sendRawTransaction', ['0x00']), /does not submit/); });
test('app action guards reject incomplete registration and unready claims', () => { const b = complete(), s = { positions: [{ network: 'solana', phase: 'locked', walletUsdcRaw: '1000000', claimableRaw: '0' }], linked: false, claimable: false, canPrepare: false, phase: 'saving' } as GoalChainState; assert.throws(() => assertActionState(s, { id: 'x', network: 'solana', action: 'deposit', amountRaw: '1000000' })); assert.throws(() => assertActionState({ ...s, linked: true }, { id: 'x', network: 'solana', action: 'prepare' })); assert.throws(() => assertActionState({ ...s, linked: true }, { id: 'x', network: 'solana', action: 'claim', amountRaw: '1' })); });
const position = (network: GoalPositionState['network'], domain: GoalPositionState['domain']): GoalPositionState => ({ network, domain, phase: 'locked', initialized: true, registered: true, linked: true, assetsRaw: '2000000', principalRaw: '2000000', claimedRaw: '0', claimableRaw: '0', walletUsdcRaw: '18000000', nativeBalanceRaw: '100000000', strategyReceiptRaw: '0', round: '0', commandSequence: '0', reportSequence: '0', progressSequence: '1', ready: false, reservedRaw: '0', observation: '100' });
const decoded = (b: GoalBinding): DecodedGoal => ({ owner: b.owner.solana, goalId: b.goalId, target: 8000000n, principal: 2000000n, claimed: 0n, round: 0n, outboundSequence: 0n, localReserved: 0n, localReadySlot: 0n, achievedTotal: 0n, localReady: false, phase: 0, bump: 1, participants: b.participants.map(p => ({ domain: p.domain, eid: p.eid, asset: '0x' + addressWord(p.asset), router: '0x' + addressWord(p.router), vault: '0x' + addressWord(p.vault!), owner: '0x' + addressWord(b.owner.evm), configHash: p.configHash!, linked: true, netAssets: 2000000n, progressSequence: 1n, observation: 100n, observedAt: BigInt(Math.floor(Date.now() / 1000)), receivedAt: BigInt(Math.floor(Date.now() / 1000)), inboundSequence: 0n, reserved: 0n, ready: false, abortAck: false })) });
test('prepare eligibility requires this goal fresh authenticated NAV, registration, matching live balances and cash-only positions', () => { const b = complete(), g = decoded(b), positions = [position('solana', 1), position('base', 2), position('arbitrum', 3), position('ethereum', 4)]; assert.equal(combineState(b, positions, g, 123).canPrepare, true); const stale = structuredClone(g); stale.participants[0]!.receivedAt = 1n; assert.equal(combineState(b, positions, stale, 123).canPrepare, false); const mismatched = structuredClone(positions); mismatched[2]!.assetsRaw = '1999999'; assert.equal(combineState(b, mismatched, g, 123).canPrepare, false); const unlinked = structuredClone(positions); unlinked[3]!.registered = false; assert.equal(combineState(b, unlinked, g, 123).canPrepare, false); const earning = structuredClone(positions); earning[1]!.strategyReceiptRaw = '1'; assert.equal(combineState(b, earning, g, 123).canPrepare, false); assert.equal(combineState({ ...b, targetRaw: '9000000' }, positions, { ...g, target: 9000000n }, 123).canPrepare, false); });
test('permanent achievement remains authoritative after all four balances reach zero', () => {
    const b = complete(), g = decoded(b), positions = [position('solana', 1), position('base', 2), position('arbitrum', 3), position('ethereum', 4)];
    g.phase = 3;
    g.achievedTotal = 8000000n;
    g.claimed = 2000000n;
    for (const p of positions)
        Object.assign(p, { phase: 'achieved', assetsRaw: '0', claimedRaw: '2000000' });
    const state = combineState(b, positions, g, 123);
    assert.equal(state.phase, 'claimed');
    assert.equal(state.achievedTotalRaw, '8000000');
    assert.equal(state.totalClaimedRaw, '8000000');
    assert.equal(state.totalAssetsRaw, '0');
    assert.equal(state.claimable, false);
    assert.equal(state.canPrepare, false);
});
import { TransactionMessage, VersionedTransaction } from '@solana/web3.js';
import { assertUsablePlan } from '../src/chain/planner.js';
import { SOLANA_DEPLOYMENT } from '@nabungfi/shared/chain';
function solPlan(b: GoalBinding): ChainPlan { const blockhash = b.solanaGoal, tx = new VersionedTransaction(new TransactionMessage({ payerKey: new PublicKey(b.owner.solana), recentBlockhash: blockhash, instructions: [financialInstruction(b, 'claim', '1000000')] }).compileToV0Message()), unsigned = { id: 'sol-step', goalId: b.goalId, action: 'claim' as const, network: 'solana' as const, owner: b.owner.solana, amountRaw: '1000000', createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60000).toISOString(), transaction: { kind: 'solana' as const, chainId: 'solana-devnet' as const, base64: Buffer.from(tx.serialize()).toString('base64'), blockhash, lastValidBlockHeight: 120 } }; return { ...unsigned, fingerprint: planFingerprint(unsigned) }; }
test('wallet-start gate accepts the final valid Solana height and rejects the next height before signing', async () => { const b = complete(), p = solPlan(b); let height = 120, valid = true, validityCalls = 0; const rpc = { solana: { getGenesisHash: async () => SOLANA_DEPLOYMENT.genesis, getBlockHeight: async () => height, isBlockhashValid: async () => { validityCalls++; return { value: valid }; }, simulateTransaction: async () => ({ value: { err: null } }) } } as unknown as RpcTransport; await assertUsablePlan(rpc, b, p); assert.equal(validityCalls, 1); height = 121; await assert.rejects(assertUsablePlan(rpc, b, p), (e: any) => e.code === 'PLAN_EXPIRED'); assert.equal(validityCalls, 1); height = 120; valid = false; await assert.rejects(assertUsablePlan(rpc, b, p), (e: any) => e.code === 'PLAN_EXPIRED'); });
test('wallet-start RPC failure never becomes a usable plan and unsigned payload has no signatures', async () => { const b = complete(), p = solPlan(b), rpc = { solana: { getGenesisHash: async () => { throw new Error('RPC unavailable'); } } } as unknown as RpcTransport; await assert.rejects(assertUsablePlan(rpc, b, p)); const tx = VersionedTransaction.deserialize(Buffer.from((p.transaction as any).base64, 'base64')); assert(tx.signatures.every(sig => sig.every(n => n === 0))); });
test('recomputed fingerprint cannot authorize a substituted canonical method or Solana instruction', () => { const b = complete(), p = plan(b), bad = { ...p, transaction: { ...(p.transaction as any), data: '0x' + ABI.claim + word('1000000') } }; const { fingerprint, ...raw } = bad; bad.fingerprint = planFingerprint(raw); assert.throws(() => assertPlan(b, bad)); const s = solPlan(b), renamed = { ...s, action: 'deposit' as const }; const { fingerprint: f, ...u } = renamed; renamed.fingerprint = planFingerprint(u); assert.throws(() => assertPlan(b, renamed)); });
test('failed EVM receipt still requires canonical block, plan chronology and confirmation depth', async () => { const b = complete(), p = plan(b), hash = '0x' + '5'.repeat(64), blockHash = '0x' + '6'.repeat(64), tx: EvmTransaction = { hash, from: p.owner, to: (p.transaction as any).to, input: (p.transaction as any).data, value: '0x0', chainId: '0x14a34' }; let block = { hash: blockHash, timestamp: '0x' + Math.floor(Date.now() / 1000).toString(16) }, latest = '0x11'; const receipt: EvmReceipt = { transactionHash: hash, status: '0x0', blockNumber: '0x10', blockHash, logs: [] }; const rpc = { call: async (_network: string, method: string) => ({ eth_chainId: '0x14a34', eth_getTransactionByHash: tx, eth_getTransactionReceipt: receipt, eth_getBlockByNumber: block, eth_blockNumber: latest })[method] } as unknown as RpcTransport; assert.equal((await reconcile(rpc, b, p, hash)).status, 'failed'); latest = '0x10'; assert.equal((await reconcile(rpc, b, p, hash)).status, 'pending'); latest = '0x11'; block = { ...block, timestamp: '0x1' }; assert.equal((await reconcile(rpc, b, p, hash)).status, 'attention'); block = { ...block, hash: '0x' + '7'.repeat(64) }; assert.equal((await reconcile(rpc, b, p, hash)).status, 'pending'); });
test('malformed Solana signature size is rejected before any receipt RPC', async () => { const b = complete(), p = solPlan(b); let reads = 0; const rpc = { solana: { getGenesisHash: async () => { reads++; return SOLANA_DEPLOYMENT.genesis; } } } as unknown as RpcTransport; await assert.rejects(reconcile(rpc, b, p, '2'.repeat(80)), (e: any) => e.code === 'INVALID_TRANSACTION_HASH'); assert.equal(reads, 0); });
import { assertEvmGasFunds } from '../src/chain/planner.js';
test('owner gas gate rejects one-wei wallets against real estimated gas cost before signing', async () => { let balance = 1n; const rpc = { call: async (_network: string, method: string) => ({ eth_estimateGas: '0x5208', eth_gasPrice: '0x3b9aca00', eth_getBalance: '0x' + balance.toString(16) })[method] } as unknown as RpcTransport; const tx = { to: '0x' + '2'.repeat(40), data: '0x', value: '0x0' }; await assert.rejects(assertEvmGasFunds(rpc, 'base', owner.evm, tx), (e: any) => e.code === 'INSUFFICIENT_GAS'); balance = 25200000000000n; await assertEvmGasFunds(rpc, 'base', owner.evm, tx); });
