[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nabungfi = "Fg6PaFpoGXkYsidMpWxqSWY6W2BeZ7FEfcYkgMQHGKqF"
nabungfi_lz = "6Ckm2BrnXxsSjyG5b17kQQRjoECVrts92RKXVGT8XeqS"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace --locked"
