import{createRequire}from'node:module';import{readFileSync}from'node:fs';import{join}from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import assert from'node:assert/strict';
import{CORE_V2,TRANSPORT_V2,STORE_V2,multichainGoal,decodeMultichainGoal,ownerActionV2,balanceActionV2,transportQuoteV2,transportSendV2}from'../../solana/script/multichain-instructions.mjs';
import{multichainRouteContext,multichainPacketAccounts,verifyMultichainRoute}from'../../solana/script/multichain-layerzero.mjs';
import{selector,addressWord,bytesCall,solReceiveOptions,evmReceiveOptions,keccak}from'./abi.mjs';import{fingerprint,loadState,atomicWrite}from'./persistence.mjs';import{reserveNativeBudget}from'./budgets.mjs';import{verifySignedTransaction}from'./signing.mjs';
const require=createRequire(process.env.NABUNGFI_LZ_PACKAGE_JSON||new URL('../../solana/package.json',import.meta.url));const web3=require('@solana/web3.js'),bs58module=require('bs58'),bs58=bs58module.default||bs58module;const runFile=promisify(execFile);const hex=n=>`0x${BigInt(n).toString(16)}`;
import{validateSolanaSigner,assertCoordinationAction}from'./authority.mjs';
import{preparedPlanIdentity}from'./prepared-plan.mjs';
export class ChainAdapter{
 #authorizedPlans=new WeakMap();
 #authorize(goal,plan){this.#authorizedPlans.set(plan,{goal:structuredClone(goal),identity:preparedPlanIdentity(plan)});return plan;}
 constructor(config){this.config=config;this.signer=web3.Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(config.solana.signerPath,'utf8'))));validateSolanaSigner(config,config.goals,this.signer.publicKey.toBase58());this.connection=new web3.Connection(config.solana.rpc,{commitment:'confirmed',fetch:(input,init)=>fetch(input,{...init,signal:AbortSignal.timeout(20000)})});this.budgetPath=join(config.stateDirectory,'budgets.json');this.cycleActions=0;this.routes=new Map();}
 async request(network,payload,retry=true){
  for(let attempt=0;attempt<3;attempt++){
   try{const response=await fetch(network.rpc,{signal:AbortSignal.timeout(20000),method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});assert(response.ok,'RPC HTTP failed');const result=await response.json();assert(!result.error&&(!Array.isArray(result)||result.every(r=>!r.error)),'RPC response error');return result;}
   catch{if(!retry||attempt===2)throw new Error('RPC operation unavailable (provider output suppressed)');await new Promise(resolve=>setTimeout(resolve,750*(attempt+1)));}
  }
 }
 async rpc(network,method,params){const response=await this.request(network,{jsonrpc:'2.0',id:1,method,params},method!=='eth_sendRawTransaction');return response.result;}
 async batch(network,calls){const results=await this.request(network,calls.map((c,i)=>({jsonrpc:'2.0',id:i+1,method:'eth_call',params:[c.tx,c.block]})));assert(Array.isArray(results),'RPC batch unsupported');return calls.map((_,i)=>{const r=results.find(r=>r.id===i+1);assert(r&&!r.error,'Pinned snapshot getter failed');return r.result;});}

 context(domain){if(!this.routes.has(domain)){const env={SOLANA_MULTICHAIN_RPC_URL:this.config.solana.rpc};for(const n of this.config.networks)env[`MULTI_${({2:'BASE_SEPOLIA',3:'ARBITRUM_SEPOLIA',4:'ETHEREUM_SEPOLIA'})[n.domain]}_ROUTER`]=n.router;const c=multichainRouteContext(env,domain),rpc=c.rpc;c.rpc=new Proxy(rpc,{get(t,p){const v=t[p];if(typeof v!=='function'||p==='getEndpoint'||p==='getCluster')return typeof v==='function'?v.bind(t):v;return(...args)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('LayerZero read RPC timed out')),20000);Promise.resolve(v.apply(t,args)).then(resolve,reject).finally(()=>clearTimeout(timer));});}});this.routes.set(domain,c);}return this.routes.get(domain);}
 async validate(){assert.equal(await this.connection.getGenesisHash(),'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG');for(const network of this.config.networks){assert.equal(BigInt(await this.rpc(network,'eth_chainId',[])),BigInt(network.chainId));assert.equal((await verifyMultichainRoute(this.context(network.domain))).sealed,true);}}
 async snapshot(goal){const g=multichainGoal({...goal,target:goal.targetRaw});const response=await this.connection.getMultipleAccountsInfoAndContext([g.goal,g.cash].map(a=>new web3.PublicKey(a)),{commitment:'confirmed'});assert(response.value.every(Boolean));assert.equal(response.value[0].owner.toBase58(),CORE_V2);assert.equal(response.value[1].owner.toBase58(),'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');assert.equal(new web3.PublicKey(response.value[1].data.subarray(0,32)).toBase58(),'4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU');assert.equal(new web3.PublicKey(response.value[1].data.subarray(32,64)).toBase58(),g.goal);const sol=decodeMultichainGoal(response.value[0].data);assert.equal(sol.owner,g.owner);assert.equal(sol.goalId,g.goalId.toLowerCase());assert.equal(sol.target,g.target);assert.equal(sol.participants.length,g.participants.length);const peers=[];
  for(const p of g.participants){const n=this.config.networks.find(n=>n.domain===p.domain),block=await this.rpc(n,'eth_blockNumber',[]);const getters=[['registered',n.router,'isGoalRegistered(address)',addressWord(p.vault)],['isVault',n.router,'isVault(address)',addressWord(p.vault)],['asset',p.vault,'asset()'],['evmOwner',p.vault,'owner()'],['goalId',p.vault,'goalId()'],['configHash',p.vault,'configHash()'],['sourceCoordinator',p.vault,'sourceCoordinator()'],['target',p.vault,'target()'],['destinationDomain',p.vault,'destinationDomain()'],['messenger',p.vault,'messenger()'],['evmPhase',p.vault,'phase()'],['round',p.vault,'currentRound()'],['commandSequence',p.vault,'commandSequence()'],['reportSequence',p.vault,'reportSequence()'],['evmProgressSequence',p.vault,'progressSequence()'],['totalAssets',p.vault,'totalAssets()'],['receiptBalance',p.vault,'strategyReceiptBalance()'],['preparedAssets',p.vault,'preparedAssets()']];const values=await this.batch(n,getters.map(([,to,sig,arg])=>({tx:{to,data:`${selector(sig)}${arg||''}`},block})));const e=Object.fromEntries(getters.map(([name],i)=>[name,values[i]]));assert.equal(BigInt(e.isVault),1n);assert.equal(e.asset.slice(-40).toLowerCase(),p.asset.slice(2).toLowerCase());assert.equal(e.evmOwner.slice(-40).toLowerCase(),p.owner.slice(2).toLowerCase());assert.equal(e.goalId,g.goalId.toLowerCase());assert.equal(e.configHash,p.configHash);assert.equal(e.sourceCoordinator,`0x${new web3.PublicKey(g.goal).toBuffer().toString('hex')}`);assert.equal(BigInt(e.target),g.target);assert.equal(BigInt(e.destinationDomain),BigInt(p.domain));assert.equal(e.messenger.slice(-40).toLowerCase(),p.router.slice(2).toLowerCase());const sp=sol.participants.find(x=>x.domain===p.domain);assert(sp&&sp.eid===p.eid&&sp.configHash===p.configHash);peers.push({...sp,registered:BigInt(e.registered)===1n,evmPhase:Number(BigInt(e.evmPhase)),round:BigInt(e.round).toString(),commandSequence:BigInt(e.commandSequence).toString(),reportSequence:BigInt(e.reportSequence).toString(),evmProgressSequence:BigInt(e.evmProgressSequence).toString(),totalAssets:BigInt(e.totalAssets).toString(),receiptBalance:BigInt(e.receiptBalance).toString(),preparedAssets:BigInt(e.preparedAssets).toString(),block});}
  return JSON.parse(JSON.stringify({sol,peers,slot:response.context.slot,localCash:response.value[1].data.readBigUInt64LE(64)},(_,v)=>typeof v==='bigint'?v.toString():v));
 }
 async prepare(goal,action,snapshot){assertCoordinationAction(this.config,goal,action,this.signer.publicKey.toBase58());const g=multichainGoal({...goal,target:goal.targetRaw});if(['register','command','prepare','local-ready','achieve'].includes(action.kind)){let instructions;if(action.kind==='prepare')instructions=[ownerActionV2(g,'begin_prepare')];else if(action.kind==='local-ready')instructions=[balanceActionV2(g,'mark_local_ready')];else if(action.kind==='achieve')instructions=[balanceActionV2(g,'achieve')];else{const payer=this.signer.publicKey.toBase58(),c=this.context(action.domain),metas=await multichainPacketAccounts(c,payer),options=evmReceiveOptions(500000),quote=transportQuoteV2(g,action.domain,action.sequence,options,metas.quote),block=await this.connection.getLatestBlockhash('confirmed'),tx=new web3.VersionedTransaction(new web3.TransactionMessage({payerKey:this.signer.publicKey,recentBlockhash:block.blockhash,instructions:[quote]}).compileToV0Message());tx.sign([this.signer]);const{value}=await this.connection.simulateTransaction(tx,{sigVerify:true,commitment:'confirmed'});assert(!value.err,'Solana quote failed');const bytes=Buffer.from(value.returnData.data[0],'base64');assert.equal(bytes.length,16);assert.equal(bytes.readBigUInt64LE(8),0n);const fee=bytes.readBigUInt64LE();assert(fee>0n&&fee<=BigInt(this.config.solana.messageFeeCap));instructions=[web3.ComputeBudgetProgram.setComputeUnitLimit({units:this.config.solana.computeUnitCap}),transportSendV2(g,payer,action.domain,action.sequence,fee,options,metas.send)];}
    const lifetime=await this.connection.getLatestBlockhash('confirmed'),tx=new web3.VersionedTransaction(new web3.TransactionMessage({payerKey:this.signer.publicKey,recentBlockhash:lifetime.blockhash,instructions}).compileToV0Message());tx.sign([this.signer]);assert(tx.serialize().length<=1232);const{value}=await this.connection.simulateTransaction(tx,{sigVerify:true,commitment:'confirmed'});assert(!value.err,'Solana action simulation failed');const txFee=(await this.connection.getFeeForMessage(tx.message,'confirmed')).value;assert(txFee!==null);const nativeFee=action.kind==='register'||action.kind==='command'?tx.message.compiledInstructions.length&&Buffer.from(instructions[1].data).readBigUInt64LE(20):0n;const spend=BigInt(txFee)+BigInt(nativeFee);const balance=BigInt(await this.connection.getBalance(this.signer.publicKey,'confirmed'));assert(balance-spend>=BigInt(this.config.solana.minNativeBalance),'Solana reserve floor');return this.#authorize(goal,{network:'solana',tx,units:value.unitsConsumed,spend:spend.toString(),lifetime,action,instructions});
  }
  const network=this.config.networks.find(n=>n.domain===action.domain),p=g.participants.find(p=>p.domain===action.domain),options=solReceiveOptions(this.config.policy.solReceiveCompute,this.config.policy.solReceiveLamports);let to,data,value='0';
  if(action.kind==='ready'){to=p.vault;data=selector('markReady()');}
  else{to=p.router;const names=action.kind==='ack'?['quoteRegistration(address,bytes)','sendRegistration(address,bytes)']:action.kind==='progress'?['quoteProgress(address,bytes)','sendProgress(address,bytes)']:['quoteReport(address,uint64,bytes)','sendReport(address,uint64,bytes)'];const sequence=action.kind==='report'?action.sequence:undefined;const quoted=await this.rpc(network,'eth_call',[{to,from:this.config.evm.signerAddress,data:bytesCall(names[0],p.vault,sequence,options)},'latest']);assert.equal(quoted.length,130);const fee=BigInt(`0x${quoted.slice(2,66)}`);assert.equal(BigInt(`0x${quoted.slice(66)}`),0n);assert(fee>0n&&fee<=BigInt(network.messageFeeCap));value=fee.toString();data=bytesCall(names[1],p.vault,sequence,options);}
  const tx={to,from:this.config.evm.signerAddress,data,value:hex(value)};await this.rpc(network,'eth_call',[tx,'latest']);const gas=BigInt(await this.rpc(network,'eth_estimateGas',[tx]));const gasLimit=(gas*120n+99n)/100n;assert(gasLimit<=BigInt(network.gasLimitCap));const price=BigInt(await this.rpc(network,'eth_gasPrice',[]))*2n;assert(price>0n&&price<=BigInt(network.gasPriceCap));const latest=BigInt(await this.rpc(network,'eth_getTransactionCount',[this.config.evm.signerAddress,'latest'])),pending=BigInt(await this.rpc(network,'eth_getTransactionCount',[this.config.evm.signerAddress,'pending']));assert.equal(latest,pending,'External EVM pending nonce; do not compete');const spend=BigInt(value)+gasLimit*price*2n;const balance=BigInt(await this.rpc(network,'eth_getBalance',[this.config.evm.signerAddress,'latest']));assert(balance-spend>=BigInt(network.minNativeBalance),'EVM reserve floor');return this.#authorize(goal,{network:`evm-${network.domain}`,chain:network,tx,nonce:latest.toString(),gasLimit:gasLimit.toString(),gasPrice:price.toString(),value,spend:spend.toString(),action,units:gas.toString()});
 }
 async sign(b){const authorized=this.#authorizedPlans.get(b);assert(authorized,'Signing requires an adapter-produced coordinated plan');assert.equal(preparedPlanIdentity(b),authorized.identity,'Prepared bytes or financial parameters changed');assertCoordinationAction(this.config,authorized.goal,b.action,this.signer.publicKey.toBase58());this.#authorizedPlans.delete(b);if(b.network==='solana'){const wire=Buffer.from(b.tx.serialize()).toString('base64');return{...b,hash:bs58.encode(b.tx.signatures[0]),wire,lifetime:{blockhash:b.lifetime.blockhash,lastValidBlockHeight:b.lifetime.lastValidBlockHeight},signer:this.signer.publicKey.toBase58(),instructionHash:fingerprint(b.instructions.map(ix=>({program:ix.programId.toBase58(),keys:ix.keys.map(k=>({address:k.pubkey.toBase58(),signer:k.isSigner,writable:k.isWritable})),data:ix.data.toString('hex')}))),fee:b.spend};}
  const signer=this.config.evm,argv=['mktx',b.tx.to,b.tx.data,'--account',signer.account,'--rpc-url',b.chain.rpc,'--chain',String(b.chain.chainId),'--nonce',b.nonce,'--gas-limit',b.gasLimit,'--gas-price',b.gasPrice,'--legacy','--value',b.value,...(signer.emptyPassword?['--password','']:['--password-file',signer.passwordFile])];let result;try{result=await runFile(signer.executable,[...(signer.prefixArgs||[]),...argv],{maxBuffer:1024*1024,timeout:120000});}catch{throw new Error('Encrypted Foundry signing failed; no private key or raw transaction printed');}const wire=result.stdout.trim();assert(/^0x[\da-f]+$/i.test(wire),'Signer returned invalid transaction');await verifySignedTransaction(signer,wire,{...b,hash:keccak(wire)});return{...b,wire,hash:keccak(wire),signer:signer.signerAddress,instructionHash:fingerprint({to:b.tx.to,data:b.tx.data,value:b.value,chainId:b.chain.chainId,nonce:b.nonce,gasLimit:b.gasLimit,gasPrice:b.gasPrice}),fee:b.spend};
 }
 reserveBudget(prepared,intent){const cycle={actions:this.cycleActions};reserveNativeBudget(this.budgetPath,this.config,prepared,intent,cycle);this.cycleActions=cycle.actions;}
 async broadcast(p){if(p.network==='solana'){const signature=await this.connection.sendRawTransaction(Buffer.from(p.wire,'base64'),{preflightCommitment:'confirmed',maxRetries:4});assert.equal(signature,p.hash);return signature;}const n=p.chain||this.config.networks.find(n=>`evm-${n.domain}`===p.network);const result=await this.rpc(n,'eth_sendRawTransaction',[p.wire]);assert.equal(result.toLowerCase(),p.hash.toLowerCase());return result;}
 async reconcile(e){if(e.network==='solana'){const{value:[s]}=await this.connection.getSignatureStatuses([e.hash],{searchTransactionHistory:true});if(s?.err)return{state:'failed',code:'solana-transaction-failed'};if(s?.confirmationStatus==='confirmed'||s?.confirmationStatus==='finalized')return{state:'confirmed',receipt:{slot:s.slot,confirmation:s.confirmationStatus}};if(await this.connection.getBlockHeight('confirmed')>e.lifetime.lastValidBlockHeight)return{state:'ambiguous',code:'expired-without-receipt'};return{state:'pending'};}const n=this.config.networks.find(n=>`evm-${n.domain}`===e.network),receipt=await this.rpc(n,'eth_getTransactionReceipt',[e.hash]);if(receipt){if(receipt.status!=='0x1')return{state:'failed',code:'evm-transaction-failed'};return{state:'confirmed',receipt:{blockNumber:receipt.blockNumber,transactionHash:receipt.transactionHash}};}const latest=BigInt(await this.rpc(n,'eth_getTransactionCount',[e.signer,'latest']));if(latest>BigInt(e.nonce))return{state:'ambiguous',code:'nonce-consumed-without-original-receipt'};return{state:'pending'};}
}
