import assert from'node:assert/strict';import{resolve}from'node:path';import{readFileSync}from'node:fs';
import{multichainGoal,CORE_V2,TRANSPORT_V2,STORE_V2,EIDS_V2}from'../../solana/script/multichain-instructions.mjs';
export function readConfig(path){const c=JSON.parse(readFileSync(path,'utf8'));assert.equal(c.version,1);assert.equal(c.profile,'nabungfi-v2-devnet-four-chain');assert.equal(c.solana.core,CORE_V2);assert.equal(c.solana.transport,TRANSPORT_V2);assert.equal(c.solana.store,STORE_V2);assert(c.solana.rpc&&c.solana.signerPath&&c.evm.account&&c.evm.signerAddress);assert(c.stateDirectory&&c.signerLockFile);c.stateDirectory=resolve(c.stateDirectory);c.signerLockFile=resolve(c.signerLockFile);assert(c.stateDirectory.split(/[\\/]/).includes('.local'),'Keeper state must remain in an ignored .local directory');
 assert(c.networks.length===3&&new Set(c.networks.map(n=>n.domain)).size===3);assert(c.solana.signerPath&&c.evm.executable&&c.evm.account==='deployer-wallet');assert(typeof c.evm.emptyPassword==='boolean');if(!c.evm.emptyPassword)assert(c.evm.passwordFile);assert(c.signerLockFile.split(/[\\/]/).includes('.local'));for(const field of['solReceiveCompute','solReceiveLamports'])assert(Number.isSafeInteger(c.policy[field])&&c.policy[field]>=0);assert(c.policy.solReceiveCompute>=200000&&c.policy.solReceiveCompute<=1000000);assert(c.policy.solReceiveLamports<=10000000);
 assert(c.goals.length>=1&&c.goals.length<=20);assert(new Set(c.goals.map(g=>g.goalId.toLowerCase())).size===c.goals.length);assert(c.intervalMs>=5000&&c.intervalMs<=3600000);assert(c.policy.progressRefreshMs>=30000&&c.policy.maxProgressAgeMs>=c.policy.progressRefreshMs);assert(c.policy.clockSkewMs>=0&&c.policy.clockSkewMs<=30000);assert(c.policy.sameWireRetryMs>=30000&&c.policy.maxSameWireRetries>=0&&c.policy.maxSameWireRetries<=4);
 for(const field of['maxActionsPerCycle','maxActionsPerDay'])assert(c.policy[field]>=1&&c.policy[field]<=1000);
 for(const domain of[2,3,4]){const network=c.networks.find(n=>n.domain===domain);assert(network&&network.eid===EIDS_V2[domain]);assert.equal(network.chainId,({2:84532,3:421614,4:11155111})[domain]);assert(network.rpc&&/^0x[\da-f]{40}$/i.test(network.router));for(const field of['messageFeeCap','dailySpendCap','minNativeBalance','gasPriceCap'])assert(BigInt(network[field])>0n);assert(network.gasLimitCap>=100000&&network.gasLimitCap<=1000000);}
 for(const field of['messageFeeCap','dailySpendCap','minNativeBalance'])assert(BigInt(c.solana[field])>0n);assert(c.solana.computeUnitCap>=250000&&c.solana.computeUnitCap<=1000000);
 c.goals=c.goals.map(goal=>{assert(typeof goal.autoPrepare==='boolean');assert(Number(goal.maxAutoPrepareRounds??1)>=1&&Number(goal.maxAutoPrepareRounds??1)<=10);const g=multichainGoal(goal);assert.equal(g.participants.length,3);for(const p of g.participants){const n=c.networks.find(n=>n.domain===p.domain);assert.equal(p.router.toLowerCase(),n.router.toLowerCase());assert.equal(p.asset.toLowerCase(),n.asset.toLowerCase());assert.equal(p.owner.toLowerCase(),c.evm.signerAddress.toLowerCase());}return{...goal,...g,id:undefined,targetRaw:g.target.toString(),target:g.target.toString()};});return c;}
