import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,readFileSync,writeFileSync,statSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{atomicWrite,persistWire,originalWire,acquireSignerLock,loadState,fingerprint}from'../src/persistence.mjs';import{runGoal}from'../src/engine.mjs';import{runCycle}from'../src/cycle.mjs';import{reserveNativeBudget}from'../src/budgets.mjs';
const dir=()=>mkdtempSync(join(tmpdir(),'nabungfi-keeper-'));const goal={name:'car',goalId:'0x'+'1'.repeat(64)},snapshot={sol:{phase:0},peers:[{domain:2,registered:false}]};const config=d=>({stateDirectory:d,goals:[goal],policy:{sameWireRetryMs:30000,maxSameWireRetries:2,maxActionsPerDay:10,maxActionsPerCycle:10},solana:{dailySpendCap:'100'},networks:[]});
const prepared={network:'solana',hash:'original',wire:'PRIVATE_TEST_WIRE',signer:'owner',spend:'10',fee:'10',instructionHash:'instructions',lifetime:{lastValidBlockHeight:100}};
function adapter(overrides={}){return{snapshot:async()=>snapshot,prepare:async()=>({units:1}),sign:async()=>prepared,reserveBudget:()=>{},broadcast:async()=>{},reconcile:async()=>({state:'pending'}),...overrides};}
test('private wire is separate, integrity checked, never public journal content',()=>{const d=dir(),ref=persistWire(d,'sig','WIRE');assert.equal(originalWire(d,{hash:'sig',wireFile:ref}),'WIRE');writeFileSync(join(d,'wires',ref.name),'{"hash":"sig","wireHash":"bad","wire":"OTHER"}');assert.throws(()=>originalWire(d,{hash:'sig',wireFile:ref}));});
test('dry-run never rebroadcasts an existing pending original signature',async()=>{const d=dir(),c=config(d),entry={...prepared,id:'old',action:{kind:'register',domain:2,sequence:'0'},status:'submitted',signedAt:0,wireFile:persistWire(d,prepared.hash,prepared.wire)};delete entry.wire;atomicWrite(join(d,goal.goalId.slice(2)+'.json'),{allowlistHash:fingerprint(goal),intents:{old:entry}});let sends=0;await runGoal(goal,c,adapter({broadcast:async()=>{sends++;}}),false,()=>{});assert.equal(sends,0);});
test('crash after journal before send resumes identical wire, not new nonce/fee quote',async()=>{const d=dir(),c=config(d);let sends=0,quotes=0;await assert.rejects(runGoal(goal,c,adapter({broadcast:async()=>{throw Error('crash');}}),true,()=>{}));const path=join(d,goal.goalId.slice(2)+'.json'),l=loadState(path);for(const e of Object.values(l.intents))e.lastBroadcastAt=0;atomicWrite(path,l);await runGoal(goal,c,adapter({prepare:async()=>{quotes++;},broadcast:async p=>{assert.equal(p.wire,prepared.wire);assert.equal(p.hash,prepared.hash);sends++;}}),true,()=>{});assert.equal(sends,1);assert.equal(quotes,0);assert(!readFileSync(path,'utf8').includes(prepared.wire));});
test('budget reservation persists before broadcast and rejects changed signature after restart',async()=>{const d=dir(),c=config(d),p=join(d,'budgets.json'),cycle={actions:0};reserveNativeBudget(p,c,prepared,'intent',cycle);reserveNativeBudget(p,c,prepared,'intent',{actions:0});assert.throws(()=>reserveNativeBudget(p,c,{...prepared,hash:'new'},'intent',{actions:0}));assert.throws(()=>reserveNativeBudget(p,c,{...prepared,hash:'second',spend:'91'},'second',{actions:0}));});
test('global signer lock refuses races and stale takeover; release enables next owner',()=>{const p=join(dir(),'global.lock'),release=acquireSignerLock(p);assert.throws(()=>acquireSignerLock(p));release();const second=acquireSignerLock(p);second();writeFileSync(p,JSON.stringify({pid:999999,hostname:'local',id:'stale'}));assert.throws(()=>acquireSignerLock(p));});
test('corrupt state cannot silently reset the journal',()=>{const p=join(dir(),'state.json');writeFileSync(p,'');assert.throws(()=>loadState(p,{}));});
test('per-goal failures are isolated and cycle actions reset',async()=>{const d=dir(),c=config(d),logs=[];c.goals=[goal,{...goal,name:'laptop',goalId:'0x'+'2'.repeat(64)}];let observed=[];const a=adapter({snapshot:async g=>{observed.push(g.name);if(g.name==='car')throw Error('RPC outage secret URL');return{sol:{phase:3},peers:[]};}});a.cycleActions=99;await runCycle(c,a,false,e=>logs.push(e));assert.deepEqual(observed,['car','laptop']);assert.equal(a.cycleActions,0);assert(!JSON.stringify(logs).includes('secret'));});
import{initializeKeeperState}from'../src/persistence.mjs';import{unlinkSync}from'node:fs';
test('all goals are durable before first broadcast; missing first-goal journal fails restart',async()=>{const d=dir(),c=config(d);c.goals.push({...goal,name:'house',goalId:'0x'+'3'.repeat(64)});const manifest=initializeKeeperState(c);assert.equal(manifest.goals.length,2);await assert.rejects(runGoal(goal,c,adapter({broadcast:async()=>{throw Error('first broadcast interrupted');}}),true,()=>{}));unlinkSync(join(d,goal.goalId.slice(2)+'.json'));assert.throws(()=>initializeKeeperState(c),/journal missing/);});
test('changing retry/action policy or signer configuration requires explicit reconciliation',()=>{const d=dir(),c=config(d);c.evm={account:'deployer-wallet',signerAddress:'owner'};initializeKeeperState(c);assert.throws(()=>initializeKeeperState({...c,policy:{...c.policy,maxActionsPerDay:100}}),/configuration changed/);assert.throws(()=>initializeKeeperState({...c,evm:{...c.evm,account:'another'}}),/configuration changed/);assert.throws(()=>initializeKeeperState({...c,policy:{...c.policy,maxSameWireRetries:4}}),/configuration changed/);});
