// Local SBF proof: incoming verification accounts are precommitted fixtures.
// This does not stand in for public DVN/Executor delivery.
import assert from 'node:assert/strict';import{test}from'node:test';import{createRequire}from'node:module';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';
import{CORE_V2 as CORE,TRANSPORT_V2 as TRANSPORT,STORE_V2 as STORE,USDC_V2 as USDC,EIDS_V2,multichainGoal,initializeGoalV2,depositV2,ownerActionV2,balanceActionV2,claimV2,initializeTransportV2,initializePeerV2,sealTransportV2,decodeMultichainGoal,packetV2}from'../script/multichain-instructions.mjs';
const require=createRequire(process.env.NABUNGFI_TEST_PACKAGE_JSON||new URL('../package.json',import.meta.url));const{LiteSVM,FailedTransactionMetadata,Clock}=require('litesvm');const kit=require('@solana/kit');const{keccak_256}=require('@noble/hashes/sha3.js');
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');const artifacts=resolve(root,'contracts/solana/target/deploy-multichain');
const ENDPOINT='76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6',TOKEN='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',SYSTEM='11111111111111111111111111111111';
const addressBytes=a=>Buffer.from(kit.getAddressEncoder().encode(a));const disc=(type,name)=>createHash('sha256').update(`${type}:${name}`).digest().subarray(0,8);const u8=n=>Buffer.from([n]);const u32=(n,e='LE')=>{const b=Buffer.alloc(4);b[`writeUInt32${e}`](n);return b;};const u64=(n,e='LE')=>{const b=Buffer.alloc(8);b[`writeBigUInt64${e}`](BigInt(n));return b;};const pda=(program,...seeds)=>kit.getProgramDerivedAddress({programAddress:kit.address(program),seeds});
const meta=(address,w=false,s=false)=>({address:kit.address(address),role:(w?1:0)|(s?2:0)});const rawIx=(program,name,accounts,...data)=>({programAddress:kit.address(program),accounts,data:Buffer.concat([disc('global',name),...data])});const asKit=ix=>({programAddress:kit.address(ix.programId.toBase58()),accounts:ix.keys.map(a=>meta(a.pubkey.toBase58(),a.isWritable,a.isSigner)),data:ix.data});
const evm=n=>`0x${n.toString(16).padStart(2,'0').repeat(20)}`;const evmBytes=a=>Buffer.concat([Buffer.alloc(12),Buffer.from(a.slice(2),'hex')]);
function store(svm,address,owner,data){svm.setAccount({address:kit.address(address),programAddress:kit.address(owner),executable:false,data,lamports:kit.lamports(svm.minimumBalanceForRentExemption(BigInt(data.length)))});}
function mint(){return Buffer.concat([Buffer.alloc(36),u64(1_000_000_000n),u8(6),u8(1),Buffer.alloc(36)]);}
function token(owner,amount){return Buffer.concat([addressBytes(USDC),addressBytes(owner),u64(amount),Buffer.alloc(36),u8(1),Buffer.alloc(12),u64(0),Buffer.alloc(36)]);}
async function send(env,ix,success=true){env.svm.expireBlockhash();const tx=await kit.pipe(kit.createTransactionMessage({version:0}),t=>kit.setTransactionMessageFeePayerSigner(env.payer,t),t=>env.svm.setTransactionMessageLifetimeUsingLatestBlockhash(t),t=>kit.appendTransactionMessageInstruction(ix.programId?asKit(ix):ix,t),t=>kit.signTransactionMessageWithSigners(t));const result=env.svm.sendTransaction(tx);if(success&&result instanceof FailedTransactionMetadata)throw new Error(`${result.err()}\n${result.meta().logs().join('\n')}`);if(!success)assert(result instanceof FailedTransactionMetadata);return result;}
const state=e=>decodeMultichainGoal(e.svm.getAccount(kit.address(e.g.goal)).data);const amount=(e,address)=>Buffer.from(e.svm.getAccount(kit.address(address)).data).readBigUInt64LE(64);
async function environment(bootstrap=false){const svm=new LiteSVM();svm.addProgramFromFile(kit.address(CORE),resolve(artifacts,'nabungfi_multi.so'));svm.addProgramFromFile(kit.address(TRANSPORT),resolve(artifacts,'nabungfi_multi_lz.so'));const endpoint=readFileSync(resolve(root,'.local/svm-fixtures/layerzero-endpoint.so'));assert.equal(createHash('sha256').update(endpoint).digest('hex'),'caa868d80b000c488e60e99828e366e773dde877ccc92b67f81df03b608639d4');svm.addProgram(kit.address(ENDPOINT),endpoint);svm.setClock(new Clock(100n,0n,0n,0n,1_800_000_000n));const payer=await kit.generateKeyPairSigner();svm.airdrop(payer.address,kit.lamports(10_000_000_000n));const g=multichainGoal({owner:payer.address,goalId:`0x${'07'.repeat(32)}`,target:10_000_000n,participants:[2,3,4].map(domain=>({domain,eid:EIDS_V2[domain],asset:evm(domain),router:evm(domain===4?3:domain),vault:evm(domain===4?23:20+domain),owner:evm(55)}))});
 const[,bump]=await pda(TRANSPORT,Buffer.from('Store'));const[types,tbump]=await pda(TRANSPORT,Buffer.from('LzReceiveTypes'),addressBytes(STORE));
 if(!bootstrap){store(svm,STORE,TRANSPORT,Buffer.concat([disc('account','Store'),addressBytes(payer.address),addressBytes(ENDPOINT),u8(1),u8(7),u8(bump)]));store(svm,types,TRANSPORT,Buffer.concat([disc('account','LzReceiveTypesAccounts'),addressBytes(STORE),u8(tbump)]));for(const p of g.participants){const[,pbump]=await pda(TRANSPORT,Buffer.from('Peer'),addressBytes(STORE),u32(p.eid,'BE'));store(svm,p.peer,TRANSPORT,Buffer.concat([disc('account','PeerConfig'),u32(p.domain),u32(p.eid),evmBytes(p.router),u8(pbump)]));}}
 store(svm,USDC,TOKEN,mint());const source=(await kit.generateKeyPairSigner()).address;store(svm,source,TOKEN,token(payer.address,4_000_000n));const[receiver]=await pda(TRANSPORT,Buffer.from('nabung-receiver'),addressBytes(g.goal));const env={svm,payer,g,source,receiver,types};await send(env,initializeGoalV2(g));return env;}
async function inbound(e,domain,options={}){const p=e.g.participants.find(p=>p.domain===domain);const nonce=options.nonce||1n;const packet=packetV2(e.g,domain,{kind:options.kind||8,round:options.round||0n,sequence:options.sequence||0n,amount:options.amount??e.g.target,observation:100,observedAt:1_800_000_000,...options});if(options.wrongVersion)packet[4]=1;if(options.wrongDomain)packet.writeUInt32BE(options.wrongDomain,6);const sender=evmBytes(options.wrongPeer?evm(99):p.router);const guid=createHash('sha256').update(Buffer.concat([u32(domain),u64(nonce)])).digest();const[registry,rbump]=await pda(ENDPOINT,Buffer.from('OApp'),addressBytes(STORE));const[channel,nbump]=await pda(ENDPOINT,Buffer.from('Nonce'),addressBytes(STORE),u32(p.eid,'BE'),sender);const[payload,pbump]=await pda(ENDPOINT,Buffer.from('PayloadHash'),addressBytes(STORE),u32(p.eid,'BE'),sender,u64(nonce,'BE'));const[settings,sbump]=await pda(ENDPOINT,Buffer.from('Endpoint'));const[event]=await pda(ENDPOINT,Buffer.from('__event_authority'));store(e.svm,registry,ENDPOINT,Buffer.concat([disc('account','OAppRegistry'),addressBytes(STORE),u8(rbump)]));const prior=e.svm.getAccount(channel);const watermark=prior.exists?Buffer.from(prior.data).readBigUInt64LE(17):0n;store(e.svm,channel,ENDPOINT,Buffer.concat([disc('account','Nonce'),u8(nbump),u64(0),u64(nonce>watermark?nonce:watermark)]));store(e.svm,settings,ENDPOINT,Buffer.concat([disc('account','EndpointSettings'),u32(40168),u8(sbump),addressBytes(e.payer.address),u8(0)]));store(e.svm,payload,ENDPOINT,Buffer.concat([disc('account','PayloadHash'),options.wrongHash?Buffer.alloc(32):Buffer.from(keccak_256(Buffer.concat([guid,packet]))),u8(pbump)]));const params=Buffer.concat([u32(p.eid),sender,u64(nonce),guid,u32(packet.length),packet,u32(0)]);return{payload,params,ix:rawIx(TRANSPORT,'lz_receive',[meta(e.payer.address,true,true),meta(STORE),meta(p.peer),meta(e.g.goal,true),meta(e.receiver),meta(CORE),meta(TRANSPORT),meta(ENDPOINT),meta(STORE),meta(registry),meta(channel),meta(payload,true),meta(settings,true),meta(event),meta(ENDPOINT)],params)};}
async function register(e){for(const domain of[2,3,4])await send(e,(await inbound(e,domain)).ix);}

test('v2 SBF authenticates all three peers, real SPL reserves and persistent partial/full claims',async()=>{const e=await environment();await send(e,depositV2(e.g,e.source,4_000_000n),false);await send(e,(await inbound(e,2)).ix);await send(e,depositV2(e.g,e.source,4_000_000n),false);await send(e,(await inbound(e,3)).ix);await send(e,(await inbound(e,4)).ix);assert(state(e).participants.every(p=>p.linked));await send(e,depositV2(e.g,e.source,4_000_000n));assert.equal(amount(e,e.g.cash),4_000_000n);await send(e,claimV2(e.g,e.source,1n),false);await send(e,ownerActionV2(e.g,'begin_prepare'));await send(e,balanceActionV2(e.g,'mark_local_ready'));for(const domain of[2,3])await send(e,(await inbound(e,domain,{kind:4,nonce:2n,round:1n,sequence:1n,amount:2_000_000n})).ix);e.svm.warpToSlot(101n);await send(e,balanceActionV2(e.g,'achieve'),false);await send(e,(await inbound(e,4,{kind:4,nonce:2n,round:1n,sequence:1n,amount:2_000_000n})).ix);await send(e,balanceActionV2(e.g,'achieve'));assert.equal(state(e).achievedTotal,10_000_000n);await send(e,claimV2(e.g,e.source,1_000_000n));assert.equal(state(e).phase,3);assert.equal(amount(e,e.g.cash),3_000_000n);await send(e,claimV2(e.g,e.source,3_000_000n));assert.equal(amount(e,e.g.cash),0n);assert.equal(amount(e,e.source),4_000_000n);for(const domain of[2,3,4])await send(e,(await inbound(e,domain,{kind:6,nonce:3n,sequence:1n,amount:0n})).ix);assert.equal(state(e).achievedTotal,10_000_000n);assert.equal(state(e).claimed,4_000_000n);assert.equal(state(e).phase,3);});
test('v2 SBF rejects v1, wrong domain/peer/hash before consuming payload and rejects replay',async()=>{const e=await environment();for(const o of[{wrongVersion:true},{wrongDomain:4},{wrongPeer:true},{wrongHash:true}]){const v=await inbound(e,3,o);await send(e,v.ix,false);assert(e.svm.getAccount(v.payload).exists);assert(!state(e).participants[1].linked);}const v=await inbound(e,3);await send(e,v.ix);assert(!e.svm.getAccount(v.payload).exists);await send(e,v.ix,false);assert(state(e).participants[1].linked);assert(!state(e).participants[2].linked);});
test('v2 SBF zero reserve still needs all peers and abort acknowledgements form a barrier',async()=>{const e=await environment();await register(e);await send(e,ownerActionV2(e.g,'begin_prepare'));await send(e,ownerActionV2(e.g,'begin_abort'));const future=await inbound(e,3,{kind:5,nonce:3n,round:1n,sequence:2n,amount:0n});await send(e,future.ix,false);assert(e.svm.getAccount(future.payload).exists);await send(e,(await inbound(e,3,{kind:4,nonce:2n,round:1n,sequence:1n,amount:99n})).ix);assert.equal(state(e).participants[1].reserved,0n);await send(e,future.ix);await send(e,(await inbound(e,2,{kind:5,nonce:2n,round:1n,sequence:1n,amount:0n})).ix);assert.equal(state(e).phase,2);await send(e,ownerActionV2(e.g,'begin_prepare'),false);await send(e,(await inbound(e,4,{kind:5,nonce:2n,round:1n,sequence:1n,amount:0n})).ix);assert.equal(state(e).phase,0);await send(e,ownerActionV2(e.g,'begin_prepare'));assert.equal(state(e).round,2n);});
test('v2 SBF bootstrap requires the upgrade authority and exactly three immutable global peers before seal',async()=>{const e=await environment(true);const program=Buffer.from(e.svm.getAccount(TRANSPORT).data);const dataKey=kit.getAddressDecoder().decode(program.subarray(4,36));const account=e.svm.getAccount(dataKey);const data=Buffer.from(account.data);data[12]=1;addressBytes(e.payer.address).copy(data,13);e.svm.setAccount({...account,data});const stranger=await kit.generateKeyPairSigner();e.svm.airdrop(stranger.address,kit.lamports(1_000_000_000n));await send({...e,payer:stranger},initializeTransportV2(stranger.address,dataKey),false);await send(e,initializeTransportV2(e.payer.address,dataKey));await send(e,sealTransportV2(e.payer.address),false);for(const p of e.g.participants)await send(e,initializePeerV2(e.payer.address,p));await send(e,initializePeerV2(e.payer.address,e.g.participants[0]),false);await send(e,sealTransportV2(e.payer.address));assert.equal(e.svm.getAccount(STORE).data[72],1);const[registry]=await pda(ENDPOINT,Buffer.from('OApp'),addressBytes(STORE));assert.deepEqual(Buffer.from(e.svm.getAccount(registry).data).subarray(8,40),addressBytes(STORE));await send(e,initializePeerV2(e.payer.address,e.g.participants[0]),false);});

// Outbound uses the repository's explicitly test-only message library; this tests
// packet construction, CPI ABI and nonce/fee rollback, not production worker delivery.
async function outbound(e,domain){
 const TEST='4HvzfJA1PjENpgoofQxNyogKQeBqsEX54w8r8quvbgwG';e.svm.addProgramFromFile(kit.address(TEST),resolve(root,'contracts/solana/target/deploy/nabungfi_test_messagelib.so'));
 const p=e.g.participants.find(p=>p.domain===domain);const[library,lbump]=await pda(TEST,Buffer.from('MessageLib'));const[info,ibump]=await pda(ENDPOINT,Buffer.from('MessageLib'),addressBytes(library));const[custom,cbump]=await pda(ENDPOINT,Buffer.from('SendLibraryConfig'),addressBytes(STORE),u32(p.eid,'BE'));const[defaults,dbump]=await pda(ENDPOINT,Buffer.from('SendLibraryConfig'),u32(p.eid,'BE'));const[channel,nbump]=await pda(ENDPOINT,Buffer.from('Nonce'),addressBytes(STORE),u32(p.eid,'BE'),evmBytes(p.router));const[settings,sbump]=await pda(ENDPOINT,Buffer.from('Endpoint'));const[event]=await pda(ENDPOINT,Buffer.from('__event_authority'));const[record]=await pda(TEST,Buffer.from('test-record'));
 store(e.svm,info,ENDPOINT,Buffer.concat([disc('account','MessageLibInfo'),u8(0),u8(ibump),u8(lbump)]));store(e.svm,custom,ENDPOINT,Buffer.concat([disc('account','SendLibraryConfig'),addressBytes(library),u8(cbump)]));store(e.svm,defaults,ENDPOINT,Buffer.concat([disc('account','SendLibraryConfig'),addressBytes(library),u8(dbump)]));store(e.svm,channel,ENDPOINT,Buffer.concat([disc('account','Nonce'),u8(nbump),u64(0),u64(0)]));store(e.svm,settings,ENDPOINT,Buffer.concat([disc('account','EndpointSettings'),u32(40168),u8(sbump),addressBytes(e.payer.address),u8(0)]));store(e.svm,record,TEST,Buffer.concat([disc('account','Record'),Buffer.alloc(302)]));
 const quote=()=>rawIx(TRANSPORT,'quote',[meta(STORE),meta(p.peer),meta(e.g.goal),meta(ENDPOINT),meta(TEST),meta(custom),meta(defaults),meta(info),meta(settings),meta(channel)],u32(domain),u64(0),u32(2),Buffer.from([0,3]));
 const sending=(fee=10_000n,requestedDomain=domain)=>rawIx(TRANSPORT,'send',[meta(e.payer.address,false,true),meta(STORE),meta(p.peer),meta(e.g.goal),meta(ENDPOINT),meta(STORE),meta(TEST),meta(custom),meta(defaults),meta(info),meta(settings),meta(channel,true),meta(event),meta(ENDPOINT),meta(e.payer.address,true,true),meta(record,true),meta(SYSTEM)],u32(requestedDomain),u64(0),u64(fee),u32(2),Buffer.from([0,3]));
 return{quote,sending,channel,packet:()=>{const d=Buffer.from(e.svm.getAccount(record).data);assert.deepEqual(d.subarray(40,72),evmBytes(p.router));assert.equal(d.readUInt32LE(72),p.eid);return d.subarray(88,88+d.readUInt32LE(84));}};
}
test('v2 SBF quotes and sends each peer leaf with independent nonce, rejecting underpayment and domain substitution',async()=>{
 const e=await environment();const channels=[];
 for(const domain of[2,3,4]){const out=await outbound(e,domain);const quote=await send(e,out.quote());assert.equal(Buffer.from(quote.returnData().data()).readBigUInt64LE(),10_000n);await send(e,out.sending(9999n),false);assert.equal(Buffer.from(e.svm.getAccount(out.channel).data).readBigUInt64LE(9),0n);await send(e,out.sending(10_000n,domain===4?2:4),false);await send(e,out.sending());const packet=out.packet();assert.equal(packet[4],2);assert.equal(packet[5],7);assert.equal(packet.readUInt32BE(10),domain);assert.deepEqual(packet.subarray(46,78),Buffer.from(e.g.participants.find(p=>p.domain===domain).configHash.slice(2),'hex'));assert.equal(packet.readBigUInt64BE(190),10_000_000n);assert.equal(Buffer.from(e.svm.getAccount(out.channel).data).readBigUInt64LE(9),1n);channels.push(out.channel);}
 assert.equal(new Set(channels).size,3);
});
test('v2 SBF keeps multiple owner goals isolated and rejects another goal cash or receiver account',async()=>{
 const a=await environment();const g=multichainGoal({owner:a.payer.address,goalId:`0x${'08'.repeat(32)}`,target:10_000_000n,participants:a.g.participants});const[receiver]=await pda(TRANSPORT,Buffer.from('nabung-receiver'),addressBytes(g.goal));const b={...a,g,receiver};await send(b,initializeGoalV2(g));assert.notEqual(a.g.goal,b.g.goal);assert.notEqual(a.g.cash,b.g.cash);
 const incoming=await inbound(a,2);const forged={...incoming.ix,accounts:incoming.ix.accounts.map((m,i)=>i===3?meta(b.g.goal,true):m)};await send(a,forged,false);assert(!state(a).participants[0].linked);assert(!state(b).participants[0].linked);
 await register(a);await send(a,depositV2(a.g,a.source,4_000_000n));await send(a,ownerActionV2(a.g,'begin_prepare'));
 await send(a,rawIx(CORE,'mark_local_ready',[meta(a.g.goal,true),meta(b.g.cash)]),false);assert.equal(state(a).localReady,false);assert.equal(state(b).phase,0);assert.equal(state(b).principal,0n);
});
