/** Explicit real-Neon integration test. Test identities are unique and cleaned by their IDs only. */
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {once} from 'node:events';
import {writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {loadAppConfig,loadLocalEnvironment} from '../src/config.js';
import {neonDatabase,migrateDatabase} from '../src/database.js';
import {postgresRepository,fingerprint,type GoalRecord} from '../src/repository.js';
import {deriveGoalBinding} from '../src/chain/codec.js';
import {applicationServer,type ChainServices} from '../src/application-server.js';
import {ApiError} from '../src/errors.js';
import type {ChainPlan} from '@nabungfi/shared/chain';
import { GOAL_TEMPLATES } from '@nabungfi/shared/application';

loadLocalEnvironment();const config=loadAppConfig(),db=neonDatabase(config.databaseUrl),repo=postgresRepository(db);
const namespace='backend-test-'+randomUUID(),owners:string[]=[];let checks=0;
const pass=()=>{checks++;};
const owner={solana:'AMoZFFdhUaNq8qyVRE4RrdW7rBc5Jssc6b7MyERMB7s8',evm:'0xc82f469aa95a2f7792300c8d11230e9023a98600'};
const binding=(targetRaw='4000000')=>deriveGoalBinding({goalId:'0x'+randomBytes(32).toString('hex'),targetRaw,owner,networks:['solana','base','arbitrum','ethereum']});
const plan=(step:{id:string;goalId:string;action:any;network:any;amountRaw?:string}):ChainPlan=>({id:step.id,goalId:step.goalId,action:step.action,network:step.network,...(step.amountRaw?{amountRaw:step.amountRaw}:{}),owner:owner.evm,fingerprint:'test-only-'+step.id,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+300000).toISOString(),transaction:{kind:'evm',chainId:84532,to:'0x'+'2'.repeat(40),data:'0x',value:'0'}});
let server:ReturnType<typeof applicationServer>|undefined;let succeeded=false;
try{
 await migrateDatabase(db);await migrateDatabase(db);const migration=await db.query('SELECT version FROM nabungfi.schema_migrations ORDER BY version');assert.deepEqual(migration.rows.map(r=>r.version),[1,2,3,4,5,6,7,8,9,10]);pass();
 const templateOwner=await repo.user(namespace+'-templates');owners.push(templateOwner.id);
 for(const template of GOAL_TEMPLATES){const b=binding('1000000');const saved=await repo.createGoal(templateOwner.id,{name:template.label,model:template.id,targetRaw:b.targetRaw,binding:b,requestId:randomUUID(),fingerprint:fingerprint({template:template.id})});assert.equal((await repo.goal(templateOwner.id,saved.id)).model,template.id);pass();}
 const alice=await repo.user(namespace+'-alice'),bob=await repo.user(namespace+'-bob');owners.push(alice.id,bob.id);
 const createId=randomUUID(),b=binding();const input={name:'Laptop',model:'laptop' as const,targetRaw:b.targetRaw,binding:b,requestId:createId,fingerprint:fingerprint({target:b.targetRaw,name:'Laptop'})};
 const parallel=await Promise.all(Array.from({length:8},()=>repo.createGoal(alice.id,input)));assert.equal(new Set(parallel.map(g=>g.id)).size,1);pass();
 const laptop=parallel[0]!;await assert.rejects(()=>repo.createGoal(alice.id,{...input,fingerprint:'changed'}),{code:'IDEMPOTENCY_CONFLICT'});pass();
 const create=async(name:string,model:'car'|'house',target:string)=>{const b=binding(target);return repo.createGoal(alice.id,{name,model,targetRaw:target,binding:b,requestId:randomUUID(),fingerprint:fingerprint({name,target})});};
 const siblings=await Promise.all([create('Car','car','8000000'),create('House','house','12000000')]);assert.equal((await repo.goals(alice.id)).length,3);assert.equal((await repo.goals(bob.id)).length,0);assert.equal(new Set([laptop,...siblings].map(g=>g.goalId)).size,3);pass();
 const initialAdmissions=await db.query('SELECT count(*)::integer AS count FROM nabungfi.operator_admissions WHERE retired=false');const admissionCapacity=Number(initialAdmissions.rows[0]?.count)+2;
 const historical='0x'+randomBytes(32).toString('hex');const admission=await Promise.allSettled(siblings.map(g=>repo.reserveCoordinationAdmission(g.goalId,[historical],admissionCapacity)));assert.equal(admission.filter(r=>r.status==='fulfilled').length,1);assert.equal(admission.filter(r=>r.status==='rejected'&&(r.reason as ApiError).code==='OPERATOR_CAPACITY_FULL').length,1);const admittedIndex=admission.findIndex(r=>r.status==='fulfilled');assert.equal((await repo.reserveCoordinationAdmission(siblings[admittedIndex]!.goalId,[historical],admissionCapacity)).admitted,true);pass();
 const waiting=siblings[1-admittedIndex]!;await repo.reserveCoordinationAdmission(waiting.goalId,[historical],admissionCapacity,[historical]);assert.equal((await repo.goal(alice.id,siblings[admittedIndex]!.id)).goalId,siblings[admittedIndex]!.goalId);pass();
 const retireOwner=await repo.user(namespace+'-retire');owners.push(retireOwner.id);const retireBinding=binding(),retireGoal=await repo.createGoal(retireOwner.id,{name:'Retirement fixture',model:'custom',targetRaw:retireBinding.targetRaw,binding:retireBinding,requestId:randomUUID(),fingerprint:fingerprint({retireOwner:retireOwner.id})});await repo.reserveCoordinationAdmission(retireGoal.goalId,[],6);await repo.reserveCoordinationAdmission(retireGoal.goalId,[retireGoal.goalId],6,[retireGoal.goalId]);await repo.reserveCoordinationAdmission(retireGoal.goalId,[retireGoal.goalId],6);assert.equal((await db.query('SELECT retired FROM nabungfi.operator_admissions WHERE goal_id=$1',[retireGoal.goalId])).rows[0]?.retired,true);await assert.rejects(()=>db.query('UPDATE nabungfi.operator_admissions SET retired=false WHERE goal_id=$1',[retireGoal.goalId]));pass();
 const capOwner=await repo.user(namespace+'-cap');owners.push(capOwner.id);const capBinding=binding(),capInput={name:'Cap replay',model:'custom' as const,targetRaw:capBinding.targetRaw,binding:capBinding,requestId:randomUUID(),fingerprint:'cap-replay'};const firstCap=await repo.createGoal(capOwner.id,capInput);const bulk=Array.from({length:99},(_,i)=>{const b=binding();return{id:randomUUID(),goal_id:b.goalId,name:'Boundary '+i,model:'custom',target_raw:b.targetRaw,binding:b,request_id:randomUUID(),fingerprint:'boundary-'+i};});await db.query('INSERT INTO nabungfi.goals(id,owner_id,goal_id,name,model,target_raw,binding,create_request_id,create_fingerprint) SELECT x.id::uuid,$1::uuid,x.goal_id,x.name,x.model,x.target_raw::numeric,x.binding,x.request_id,x.fingerprint FROM jsonb_to_recordset($2::jsonb) AS x(id text,goal_id text,name text,model text,target_raw text,binding jsonb,request_id text,fingerprint text)',[capOwner.id,JSON.stringify(bulk)]);assert.equal((await repo.goals(capOwner.id)).length,100);const over=binding();await assert.rejects(()=>repo.createGoal(capOwner.id,{...capInput,binding:over,requestId:randomUUID()}),{code:'OWN_GOAL_CAPACITY'});assert.equal((await repo.createGoal(capOwner.id,capInput)).id,firstCap.id);assert.equal((await repo.goals(capOwner.id)).length,100);pass();
 for(const operation of [()=>repo.goal(bob.id,laptop.id),()=>repo.history(bob.id,laptop.id),()=>repo.reserveStep(bob.id,laptop.id,{requestId:randomUUID(),action:'deposit',network:'base',amountRaw:'1000000'})])await assert.rejects(operation,{code:'NOT_FOUND'});pass();
 await assert.rejects(()=>db.query('UPDATE nabungfi.goals SET target_raw=target_raw+1 WHERE id=$1',[laptop.id]));
 await assert.rejects(()=>db.query("UPDATE nabungfi.goals SET binding=jsonb_set(binding,'{participants,0,eid}','123') WHERE id=$1",[laptop.id]));pass();
 const stepInput={requestId:randomUUID(),action:'deposit' as const,network:'base' as const,amountRaw:'1000000'};
 const repeated=await Promise.all(Array.from({length:8},()=>repo.reserveStep(alice.id,laptop.id,stepInput)));assert.equal(repeated.filter(s=>s.isNew).length,1);assert.equal(new Set(repeated.map(s=>s.step.id)).size,1);pass();
 const step=repeated[0]!.step;await repo.savePlan(alice.id,laptop.id,step.id,plan(step));await assert.rejects(()=>repo.reserveStep(alice.id,laptop.id,{...stepInput,amountRaw:'2000000'}),{code:'IDEMPOTENCY_CONFLICT'});pass();
 const second=(await repo.reserveStep(alice.id,siblings[0]!.id,{...stepInput,requestId:randomUUID()})).step;await repo.savePlan(alice.id,siblings[0]!.id,second.id,plan(second));
 const hash='0x'+randomBytes(32).toString('hex');await repo.bindTransaction(alice.id,laptop.id,step.id,hash);await repo.reconciled(alice.id,laptop.id,step.id,{status:'pending',transactionHash:hash});
 const restarted=postgresRepository(db);assert.equal((await restarted.step(alice.id,laptop.id,step.id)).transactionHash,hash);await assert.rejects(()=>restarted.bindTransaction(alice.id,laptop.id,step.id,'0x'+randomBytes(32).toString('hex')),{code:'ORIGINAL_TRANSACTION_REQUIRED'});pass();
 await assert.rejects(()=>repo.bindTransaction(alice.id,siblings[0]!.id,second.id,hash),{code:'TRANSACTION_ALREADY_BOUND'});pass();
 const bobBinding=binding();const bobGoal=await repo.createGoal(bob.id,{name:'Independent test owner',model:'custom',targetRaw:bobBinding.targetRaw,binding:bobBinding,requestId:randomUUID(),fingerprint:fingerprint({owner:bob.id})});
 const bobStep=(await repo.reserveStep(bob.id,bobGoal.id,{...stepInput,requestId:randomUUID()})).step;await repo.savePlan(bob.id,bobGoal.id,bobStep.id,plan(bobStep));await repo.bindTransaction(bob.id,bobGoal.id,bobStep.id,hash);await repo.reconciled(bob.id,bobGoal.id,bobStep.id,{status:'attention',transactionHash:hash,reasonCode:'TRANSACTION_SUBSTITUTION'});pass();
 await assert.rejects(()=>db.query("UPDATE nabungfi.goal_steps SET amount_raw=amount_raw+1 WHERE id=$1",[step.id]));pass();
 await assert.rejects(()=>repo.reserveStep(alice.id,laptop.id,{...stepInput,requestId:randomUUID()}),{code:'ORIGINAL_WALLET_OUTCOME_REQUIRED'});
 assert.equal((await repo.reconciled(alice.id,laptop.id,step.id,{status:'confirmed',transactionHash:hash})).status,'confirmed');pass();
 const charlie=await repo.user(namespace+'-charlie');owners.push(charlie.id);const cb=binding(),cg=await repo.createGoal(charlie.id,{name:'Verified duplicate test',model:'custom',targetRaw:cb.targetRaw,binding:cb,requestId:randomUUID(),fingerprint:fingerprint({owner:charlie.id})});const cs=(await repo.reserveStep(charlie.id,cg.id,{...stepInput,requestId:randomUUID()})).step;await repo.savePlan(charlie.id,cg.id,cs.id,plan(cs));await repo.bindTransaction(charlie.id,cg.id,cs.id,hash);await assert.rejects(()=>repo.reconciled(charlie.id,cg.id,cs.id,{status:'confirmed',transactionHash:hash}),{code:'TRANSACTION_ALREADY_VERIFIED'});await assert.rejects(()=>db.query("UPDATE nabungfi.goal_steps SET status='pending' WHERE id=$1",[step.id]));pass();
 const unsigned=(await repo.reserveStep(alice.id,laptop.id,{...stepInput,requestId:randomUUID()})).step;const oldPlan=plan(unsigned);oldPlan.expiresAt=new Date(Date.now()-1000).toISOString();await repo.savePlan(alice.id,laptop.id,unsigned.id,oldPlan);
 await assert.rejects(()=>repo.walletStart(alice.id,laptop.id,unsigned.id,oldPlan.fingerprint),{code:'WALLET_START_REJECTED'});const freshPlan=plan(unsigned);freshPlan.fingerprint+='-refreshed';await repo.refreshPlan(alice.id,laptop.id,unsigned.id,oldPlan.fingerprint,freshPlan);pass();
 const starts=await Promise.allSettled(Array.from({length:5},()=>repo.walletStart(alice.id,laptop.id,unsigned.id,freshPlan.fingerprint)));assert.equal(starts.filter(r=>r.status==='fulfilled').length,1);assert.equal((await repo.step(alice.id,laptop.id,unsigned.id)).status,'signing');pass();
 await assert.rejects(()=>repo.refreshPlan(alice.id,laptop.id,unsigned.id,freshPlan.fingerprint,plan(unsigned)),{code:'STEP_NOT_UNSIGNED'});await assert.rejects(()=>db.query("UPDATE nabungfi.goal_steps SET status='planned' WHERE id=$1",[unsigned.id]));await assert.rejects(()=>db.query("UPDATE nabungfi.goal_steps SET plan=$1 WHERE id=$2",[JSON.stringify(plan(unsigned)),unsigned.id]));pass();
 await assert.rejects(()=>repo.reserveStep(alice.id,siblings[0]!.id,{...stepInput,requestId:randomUUID()}),{code:'ORIGINAL_WALLET_OUTCOME_REQUIRED'});await assert.rejects(()=>repo.walletStart(alice.id,siblings[0]!.id,second.id,plan(second).fingerprint),{code:'ORIGINAL_WALLET_OUTCOME_REQUIRED'});pass();
 const unsignedHash='0x'+randomBytes(32).toString('hex');await repo.bindTransaction(alice.id,laptop.id,unsigned.id,unsignedHash);await repo.reconciled(alice.id,laptop.id,unsigned.id,{status:'failed',transactionHash:unsignedHash,reasonCode:'TEST_RECEIPT_FAILED'});
 await assert.rejects(()=>repo.walletRejected(alice.id,laptop.id,unsigned.id,freshPlan.fingerprint,4001),{code:'ORIGINAL_TRANSACTION_REQUIRED'});pass();
 const canceledInput={...stepInput,requestId:randomUUID()},canceled=(await repo.reserveStep(alice.id,laptop.id,canceledInput)).step,canceledPlan=plan(canceled);await repo.savePlan(alice.id,laptop.id,canceled.id,canceledPlan);
 await assert.rejects(()=>repo.walletRejected(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint,4001),{code:'WALLET_REJECTION_NOT_ALLOWED'});await repo.walletStart(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint);await assert.rejects(()=>repo.walletRejected(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint,5001),{code:'EXPLICIT_WALLET_REJECTION_REQUIRED'});assert.equal((await repo.step(alice.id,laptop.id,canceled.id)).status,'signing');pass();
 assert.equal((await repo.walletRejected(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint,4001)).status,'rejected');const attestation=await db.query('SELECT receipt,transaction_hash FROM nabungfi.goal_steps WHERE id=$1',[canceled.id]);assert.equal((attestation.rows[0]?.receipt as any).kind,'owner-attested-wallet-rejection');assert.equal((attestation.rows[0]?.receipt as any).onchainProof,false);assert.equal(attestation.rows[0]?.transaction_hash,null);assert.equal((await repo.reserveStep(alice.id,laptop.id,canceledInput)).step.status,'rejected');assert.equal((await repo.walletRejected(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint,4001)).status,'rejected');await assert.rejects(()=>repo.walletStart(alice.id,laptop.id,canceled.id,canceledPlan.fingerprint),{code:'WALLET_START_REJECTED'});await repo.reserveStep(alice.id,laptop.id,{...stepInput,requestId:randomUUID()});pass();
 const siblingBefore=await Promise.all(siblings.map(g=>repo.goal(alice.id,g.id)));await repo.reconciled(alice.id,laptop.id,step.id,{status:'failed',transactionHash:hash,reasonCode:'TEST_RECEIPT_FAILED'});assert.deepEqual(await Promise.all(siblings.map(g=>repo.goal(alice.id,g.id))),siblingBefore);pass();
 assert.equal((await repo.listKeeperBindings()).some(g=>owners.includes(g.ownerId)),false);pass();
 let plannedCalls=0,readCalls=0,usableFailure:string|undefined;const zeroGasGoals=new Set<string>();const wrongHash='0x'+randomBytes(32).toString('hex');const chain:ChainServices={deriveGoalBinding,async readGoalState(){readCalls++;throw new Error('test RPC outage');},async assertPlanUsable(){if(usableFailure)throw new ApiError(usableFailure,409,'Controlled plan check');},async planGoalStep(b,i){plannedCalls++;if(zeroGasGoals.has(b.goalId))throw new ApiError('INSUFFICIENT_GAS',409,'Controlled zero gas');return plan({...i,goalId:b.goalId});},async reconcileGoalStep(_b,_p,h){return{status:h===wrongHash?'attention':'pending',transactionHash:h,...(h===wrongHash?{reasonCode:'TRANSACTION_SUBSTITUTION'}:{})};}};
 let admissionBlocked=true;server=applicationServer(config,repo,{async authenticate(header){if(header!=='Bearer alice-test'&&header!=='Bearer bob-test')throw new ApiError('UNAUTHENTICATED',401,'Sign in.');return{subject:namespace+(header==='Bearer alice-test'?'-alice':'-bob'),wallets:[{chainType:'solana',address:owner.solana},{chainType:'ethereum',address:owner.evm}]};}},chain,{async coordinationStatus(){return{configured:true,available:!admissionBlocked,capacity:6,registered:1,privateSignerPath:'MUST_NOT_PUBLISH'};},async assertCoordinationAdmission(b){if(admissionBlocked)throw new ApiError('OPERATOR_UNAVAILABLE',503,'Controlled coordinator unavailable');await repo.reserveCoordinationAdmission(b.goalId,[],6);}});
 server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address!=='string');const base='http://127.0.0.1:'+address.port;
 const call=async(path:string,auth='alice-test',payload?:unknown,extras:Record<string,string>={})=>{const r=await fetch(base+path,{method:payload?'POST':'GET',headers:{Authorization:'Bearer '+auth,...(payload?{'Content-Type':'application/json'}:{}),...extras},...(payload?{body:JSON.stringify(payload)}:{})});return{status:r.status,value:await r.json() as any};};
 assert.equal((await call('/api/goals','invalid')).status,401);assert.equal((await call('/api/goals/'+laptop.id,'bob-test')).status,404);assert.equal((await call('/api/goals','alice-test',undefined,{Origin:'https://untrusted.example'})).status,403);pass();
 const list=await call('/api/goals');assert.equal(list.value.goals.length,3);assert.ok(list.value.goals.every((g:any)=>g.chainState===null&&g.chainStatus==='unavailable'));assert.equal(list.value.financialReads,'detail-only');assert.equal(readCalls,0);pass();
 const session=await call('/api/session');assert.equal(session.value.user.id,alice.id);assert.equal(session.value.user.privySubject,namespace+'-alice');pass();
 for(const template of GOAL_TEMPLATES){const result=await call('/api/goals','alice-test',{name:'Template '+template.label,model:template.id,targetAmount:'1',solanaOwner:owner.solana,evmOwner:owner.evm,chains:['solana','base']},{'Idempotency-Key':randomUUID()});assert.equal(result.status,201);assert.equal(result.value.goal.model,template.id);pass();}
 const httpGoal=siblings[1]!.id;const publicConfig=await call('/api/config');assert.equal(publicConfig.value.coordinationAvailable,false);assert.equal(JSON.stringify(publicConfig.value).includes('MUST_NOT_PUBLISH'),false);assert.equal((await call('/api/goals/'+httpGoal+'/steps','alice-test',{requestId:randomUUID(),action:'create-vault',network:'base'})).status,503);assert.equal(plannedCalls,1);pass();
 admissionBlocked=false;const creation=(await call('/api/goals/'+httpGoal+'/steps','alice-test',{requestId:randomUUID(),action:'create-vault',network:'base'})).value.step;assert.ok(creation.plan);admissionBlocked=true;assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+creation.id+'/wallet-start','alice-test',{fingerprint:creation.plan.fingerprint})).status,503);assert.equal((await repo.step(alice.id,httpGoal,creation.id)).status,'planned');admissionBlocked=false;pass();
 const admissionsBefore=await db.query('SELECT count(*)::integer AS count FROM nabungfi.operator_admissions WHERE retired=false');let unusedGoalId='';
 for(let i=0;i<6;i++){const created=await call('/api/goals','alice-test',{name:'Zero gas '+i,model:'custom',targetAmount:'1',solanaOwner:owner.solana,evmOwner:owner.evm,chains:['solana','base']},{'Idempotency-Key':randomUUID()});assert.equal(created.status,201);zeroGasGoals.add(created.value.goal.goalId);unusedGoalId=created.value.goal.goalId;const failed=await call('/api/goals/'+created.value.goal.id+'/steps','alice-test',{requestId:randomUUID(),action:'create-vault',network:'base'});assert.equal(failed.status,409);assert.equal(failed.value.code,'INSUFFICIENT_GAS');}
 assert.equal((await db.query('SELECT count(*)::integer AS count FROM nabungfi.operator_admissions WHERE retired=false')).rows[0]?.count,admissionsBefore.rows[0]?.count);assert.equal(readCalls,0);pass();
 await repo.reserveCoordinationAdmission(unusedGoalId,[],6);assert.equal(await repo.releaseUnusedCoordinationAdmission(unusedGoalId),true);assert.equal(await repo.releaseUnusedCoordinationAdmission((await repo.goal(alice.id,httpGoal)).goalId),false);pass();
 const plannerBase=plannedCalls,id=randomUUID();const intent={requestId:id,action:'deposit',network:'base',amountRaw:'1'};const results=await Promise.all(Array.from({length:5},()=>call('/api/goals/'+httpGoal+'/steps','alice-test',intent)));assert.ok(results.every(r=>[200,201].includes(r.status)));assert.equal(plannedCalls,plannerBase+1);pass();
 let existing=results.find(r=>r.value.step.plan)?.value.step;assert.ok(existing);
 for(const failure of ['PLAN_EXPIRED','CHAIN_UNAVAILABLE']){usableFailure=failure;assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-start','alice-test',{fingerprint:existing.plan.fingerprint})).status,409);assert.equal((await repo.step(alice.id,httpGoal,existing.id)).status,'planned');}usableFailure=undefined;pass();
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/reconcile','alice-test',{transactionHash:wrongHash})).status,400);assert.equal((await repo.step(alice.id,httpGoal,existing.id)).transactionHash,null);pass();
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-start','alice-test',{fingerprint:existing.plan.fingerprint})).value.step.status,'signing');
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/refresh','alice-test',{fingerprint:existing.plan.fingerprint})).status,409);pass();
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-rejected','alice-test',{fingerprint:existing.plan.fingerprint,providerCode:'4001'})).status,400);assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-rejected','alice-test',{fingerprint:existing.plan.fingerprint,providerCode:4001})).value.step.status,'rejected');assert.equal((await call('/api/goals/'+httpGoal+'/steps','alice-test',intent)).value.step.status,'rejected');existing=(await call('/api/goals/'+httpGoal+'/steps','alice-test',{...intent,requestId:randomUUID()})).value.step;assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-start','alice-test',{fingerprint:existing.plan.fingerprint})).value.step.status,'signing');pass();
 const reconcile=await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/reconcile','alice-test',{transactionHash:'0x'+randomBytes(32).toString('hex')});assert.equal(reconcile.value.step.status,'pending');assert.equal((await call('/api/goals/'+httpGoal+'/history')).value.history.length,4);assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-rejected','alice-test',{fingerprint:existing.plan.fingerprint,providerCode:4001})).status,409);pass();
 const unsent=(await call('/api/goals/'+httpGoal+'/steps','alice-test',{requestId:randomUUID(),action:'approve',network:'arbitrum',amountRaw:'1'})).value.step;
 const unsentPath='/api/goals/'+httpGoal+'/steps/'+unsent.id+'/wallet-not-invoked',unsentBody={fingerprint:unsent.plan.fingerprint,attestation:'wallet-approval-never-invoked'};
 assert.equal((await call(unsentPath,'invalid',unsentBody)).status,401);assert.equal((await call(unsentPath,'bob-test',unsentBody)).status,404);assert.equal((await call(unsentPath,'alice-test',{...unsentBody,attestation:true})).status,400);assert.equal((await call(unsentPath,'alice-test',unsentBody)).status,409);pass();
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+unsent.id+'/wallet-start','alice-test',{fingerprint:unsent.plan.fingerprint})).value.step.status,'signing');assert.equal((await call(unsentPath,'alice-test',{...unsentBody,fingerprint:'different'})).status,409);assert.equal((await call(unsentPath,'alice-test',unsentBody)).value.step.reasonCode,'OWNER_ATTESTED_WALLET_NOT_INVOKED');assert.equal((await call(unsentPath,'alice-test',unsentBody)).value.step.status,'rejected');pass();
 const unsentReceipt=(await db.query('SELECT receipt,transaction_hash FROM nabungfi.goal_steps WHERE id=$1',[unsent.id])).rows[0];assert.equal((unsentReceipt?.receipt as any).kind,'owner-attested-wallet-not-invoked');assert.equal((unsentReceipt?.receipt as any).onchainProof,false);assert.equal(unsentReceipt?.transaction_hash,null);await assert.rejects(()=>repo.walletStart(alice.id,httpGoal,unsent.id,unsent.plan.fingerprint),{code:'WALLET_START_REJECTED'});pass();
 assert.equal((await call('/api/goals/'+httpGoal+'/steps/'+existing.id+'/wallet-not-invoked','alice-test',{fingerprint:existing.plan.fingerprint,attestation:'wallet-sdk-never-invoked'})).status,409);assert.equal((await repo.step(alice.id,httpGoal,existing.id)).status,'pending');pass();
 const expiredStep=(await repo.reserveStep(alice.id,laptop.id,{requestId:randomUUID(),action:'deposit',network:'solana',amountRaw:'2'})).step;
 const expiredPlan={...plan(expiredStep),owner:owner.solana,transaction:{kind:'solana',chainId:'solana-devnet',base64:'test-only-unsigned',blockhash:'test-only',lastValidBlockHeight:1}} as ChainPlan;
 await repo.savePlan(alice.id,laptop.id,expiredStep.id,expiredPlan);const expiryProof={kind:'finalized-expired-message-absence',planFingerprint:expiredPlan.fingerprint,historyCoveredBeforeCreation:true};
 await assert.rejects(()=>repo.expireUntrackedSolana(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint,expiryProof),{code:'ORIGINAL_EXPIRY_NOT_PROVEN'});await repo.walletStart(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint);await assert.rejects(()=>repo.expireUntrackedSolana(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint,{...expiryProof,historyCoveredBeforeCreation:false}),{code:'ORIGINAL_EXPIRY_NOT_PROVEN'});await assert.rejects(()=>repo.expireUntrackedSolana(bob.id,laptop.id,expiredStep.id,expiredPlan.fingerprint,expiryProof),{code:'NOT_FOUND'});pass();
 assert.equal((await repo.expireUntrackedSolana(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint,expiryProof)).reasonCode,'EXPIRED_SOLANA_MESSAGE_NOT_EXECUTED');assert.equal((await repo.expireUntrackedSolana(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint,expiryProof)).transactionHash,null);await assert.rejects(()=>repo.walletStart(alice.id,laptop.id,expiredStep.id,expiredPlan.fingerprint),{code:'WALLET_START_REJECTED'});await repo.reserveStep(alice.id,laptop.id,{requestId:randomUUID(),action:'deposit',network:'solana',amountRaw:'2'});pass();
 const spoof=await call('/api/goals','alice-test',{name:'Spoof',model:'car',targetAmount:'1',solanaOwner:owner.solana,evmOwner:'0x'+'3'.repeat(40),chains:['solana','base']},{'Idempotency-Key':randomUUID()});assert.equal(spoof.status,403);pass();
 console.log(JSON.stringify({checks,realNeon:true,migrationVersions:[1,2,3,4,5,6,7,8,9,10],financialTransactions:0,providerFixtures:'HTTP auth/chain adapters only; no fabricated chain balances'}));
 succeeded=true;
}catch{console.error('Backend database integration failed after '+checks+' checks; provider details withheld.');process.exitCode=1;}
finally{
 if(server){server.closeAllConnections();await new Promise<void>(r=>server!.close(()=>r()));}
 try{
  if(owners.length)await db.transaction(async tx=>{await tx.query('DELETE FROM nabungfi.goal_steps WHERE owner_id=ANY($1::uuid[])',[owners]);await tx.query('DELETE FROM nabungfi.operator_admissions WHERE goal_id IN (SELECT goal_id FROM nabungfi.goals WHERE owner_id=ANY($1::uuid[]))',[owners]);await tx.query('DELETE FROM nabungfi.goals WHERE owner_id=ANY($1::uuid[])',[owners]);await tx.query('DELETE FROM nabungfi.users WHERE id=ANY($1::uuid[]) AND privy_subject LIKE $2',[owners,namespace+'%']);});
  if(succeeded){const reportPath=resolve(import.meta.dirname,'../../../.local/backend-database-test-report.json');await mkdir(dirname(reportPath),{recursive:true});await writeFile(reportPath,JSON.stringify({checkedAtUtc:new Date().toISOString(),checks,realNeon:true,migrationVersions:[1,2,3,4,5,6,7,8,9,10],financialTransactions:0,cleanup:'completed; unique test owner rows only'},null,2));}
 }catch{console.error('Test-only cleanup failed; preserve unique test owner identities for private inspection.');process.exitCode=1;}
 finally{await db.close();}
}
