[package]
name = "nabungfi-lz"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "nabungfi_lz"

[features]
default = []
devnet = ["nabungfi/devnet"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build", "oapp/idl-build", "nabungfi/idl-build"]

[dependencies]
anchor-lang = "=0.32.1"
nabungfi = { path = "../nabungfi", features = ["cpi"] }
oapp = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "9c741e7f9790639537b1710a203bcdfd73b0b9ac", package = "oapp-latest" }
